### ISSUE TITLE
Spreadsheet creation not returning all parts/material calculation

### ISSUE THREAD

**Issue by Mischu1339** [FlyingGardenGnomeStudios/Inventor-Batch-Program#10]
Using Inventor 2019 
- spreadsheet function will pull all the sawcut parts, but deletes all but one at some point. 
- Sheet metal is not returned at all. 
- Purchased items in this particular assembly it was one screw short (35 instead of 36 screws)

![capture1](https://user-images.githubusercontent.com/45698233/50783961-e5f2a680-1271-11e9-8da1-84ce19d112c5.PNG)
![capture2](https://user-images.githubusercontent.com/45698233/50783963-e68b3d00-1271-11e9-9893-d890aa189bb7.PNG)
[Debug.txt](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2733717/Debug.txt)
[22902-02-0001-List.zip](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2733734/22902-02-0001-List.zip)

**Comment by Mischu1339** [comment]
Another look at it shows that it is adding all the cut parts together and not sorting based on material/shape type

**Comment by Mischu1339** [comment]
trying to do a Pack and Go for the assembly brings up this error:
![capture43](https://user-images.githubusercontent.com/45698233/50857133-55d85e00-1352-11e9-8166-c161dd6a999a.PNG)
There is nothing to update in that assembly.

**Comment by Mischu1339** [comment]
Here are the assembly files: [Workspace.zip](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2738403/Workspace.zip)

**Comment by FlyingGardenGnomeStudios** [comment]
This issue was addressed with version 2.1.3.3 please update and try again.
I have run this process with your attached files and can confirm that it is working without errors.

**Comment by Mischu1339** [comment]
Running 2.1.3.3, get the same result as before. Tried on a different system and account, same problem occurs.

**Comment by Mischu1339** [comment]
On a whim I set up a non-admin user account on my PC and ran the spreadsheet tool:

- Batch program opens another instance of Inventor
-  error pops up saying it couldn't be started (but it did)

![annotation 2019-01-15 144345](https://user-images.githubusercontent.com/45698233/51208995-c3493900-18d4-11e9-98a8-73f0070341cb.jpg)


[4725-20-0000-List.zip](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2761414/4725-20-0000-List.zip)

[Debug.txt](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2761666/Debug.txt)

- now it will return sheet area correctly
- I can watch saw cut items being listed but the totals are not calculated just the first instance of that material, but it will list the relevant file names.

**Comment by FlyingGardenGnomeStudios** [comment]
Problem apparently linked to "Project objects as construction geometry" in Tools>Application Options>Sketch
Have yet to accurately replicate the issue

**Comment by FlyingGardenGnomeStudios** [comment]
Issue resolved in V 2.1.3.15
