### ISSUE TITLE
Conversion from String to Double not valid

### ISSUE THREAD

**Issue by Mischu1339** [FlyingGardenGnomeStudios/Inventor-Batch-Program#14]
[string error.zip](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2818804/string.error.zip)

This applies only to saw cut parts:
When using the spreadsheet function, the two attached parts will conflict somehow. When the "stock number" of 801733.ipt is 801733, it will return the string error . Change the stock number to TnB 801733 it works as intended. But to confuse the issue if you place a second unique part with a number as the stock number  and delete 801733.ipt out of the assembly, the error will not occur. Now place 801733 (with "stock number" being a number) back in the assembly and now it will be the part that can't be added to the spreadsheet.
I think a workaround is not to use number only stock numbers.

**Comment by FlyingGardenGnomeStudios** [comment]
Can you link the file you are referencing again? I am not able to see it.

**Comment by Mischu1339** [comment]
[stringerror.zip](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2836730/stringerror.zip)

Everything should be in the re-attached zip file.
You should be able to recreate the issue by making an assembly with two parts with the sawcut "SC" set in iproperties, where one part has a stock number that is numerals only and one that has numbers and letters.

**Comment by FlyingGardenGnomeStudios** [comment]
Found the issue and have rectified the code accordingly. Fixed in version 3.0.0
