### ISSUE TITLE
Flat Pattern sketch

### ISSUE THREAD

**Issue by Myles240** [FlyingGardenGnomeStudios/Inventor-Batch-Program#15]
I see that you are creating a sketch to figure out the flat pattern area.  Would it be possible to delete this after the program finishes as the more times I run the batch program the more sketches I get and it really dirties up the file.

**Comment by FlyingGardenGnomeStudios** [comment]
Where is the sketch being created? I'm not seeing a new sketch on either the part or flat pattern.

**Comment by Myles240** [comment]
It was in the flat pattern... but it's all good now that you fixed it so we could use project geometry as construction lines

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
