### ISSUE TITLE
Write Protected PDF

### ISSUE THREAD

**Issue by Myles240** [FlyingGardenGnomeStudios/Inventor-Batch-Program#5]
I even deleted the previous Rev and it still came up with this error

![screenshot](https://user-images.githubusercontent.com/45576865/49403580-be5c6b80-f712-11e8-8331-baadf14e8fa6.jpg)
[2018_12_03 Debug.txt](https://github.com/FlyingGardenGnomeStudios/Inventor-Batch-Program/files/2641386/2018_12_03.Debug.txt)

**Comment by FlyingGardenGnomeStudios** [comment]
Is there any possibility someone else may have had it open on their machine?
You say you deleted the previous version, this shouldn't matter as only the current will be overwritten. Does the export succeed when you remove the current revision?

**Comment by Myles240** [comment]
He removed the current PDF to make sure no one else had it open and it still gave the error. I was a massive file... has like 16 pages

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FlyingGardenGnomeStudios** [comment]
Ok, every time I've received this error there has been a rational explanation.
You say the file is 16 pages but the screenshot you provided shows it only as 4 pages, are there multiple files sharing the same name?
If you are still unable to diagnose the issue, are you able to send me the file so I can look into it further?

**Comment by FlyingGardenGnomeStudios** [comment]
As there has been no additional information and I am unable to replicate the issue, I'm marking this as closed for the time being. Feel free to open up another if the issue arises.
