### ISSUE TITLE
Create spreadsheet material calculation incorrect

### ISSUE THREAD

**Issue by Mischu1339** [FlyingGardenGnomeStudios/Inventor-Batch-Program#7]
Creating spreadsheet returns incorrect values for saw cut and profile cut quantities (too low by 50% or more). Numbers were double checked. Could be related to this error popping up while "create spreadsheet" is running:

![capture](https://user-images.githubusercontent.com/45698233/49668840-01755200-fa25-11e8-833b-f0fef70c42f7.PNG)

**Comment by FlyingGardenGnomeStudios** [comment]
Found a few conversion commands which appeared to be causing the error.
Tested on a sawcut & profile cut assembly and values came out correct.
Fixed on V 2.1.2.4
